version: '3'
services:
  db:
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
    image: fcm-monaca-rails-db
    container_name: fcm-monaca-rails-db
    environment:
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
      PGDATA: /tmp/postgresql/data
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ../tmp/db:/tmp/postgresql/data
    ports:
      - "5432:5432"
  app:
    platform: linux/amd64 # TODO: You can delete this line if you don't use M1 mac
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    image: fcm-monaca-rails
    container_name: fcm-monaca-rails
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: password
    volumes:
      - ../:/app
      - ../tmp/cache/docker:/myapp/tmp/cache
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db

